<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Products extends \App\Entity\Products implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'option', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'categoryProducts', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'id_provider', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'categoryService', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'supprime', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'commission', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'plannedCleanings', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'directBuy', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'autoValide', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'photo', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'image'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'option', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'categoryProducts', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'id_provider', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'categoryService', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'supprime', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'commission', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'plannedCleanings', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'directBuy', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'autoValide', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'photo', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'image'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Products $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \App\Entity\Products
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description): \App\Entity\Products
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommission()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommission', []);

        return parent::getCommission();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommission($commission): \App\Entity\Products
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommission', [$commission]);

        return parent::setCommission($commission);
    }

    /**
     * {@inheritDoc}
     */
    public function getDirectBuy(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDirectBuy', []);

        return parent::getDirectBuy();
    }

    /**
     * {@inheritDoc}
     */
    public function setDirectBuy(?bool $directBuy): \App\Entity\Products
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDirectBuy', [$directBuy]);

        return parent::setDirectBuy($directBuy);
    }

    /**
     * {@inheritDoc}
     */
    public function getAutoValide(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAutoValide', []);

        return parent::getAutoValide();
    }

    /**
     * {@inheritDoc}
     */
    public function setAutoValide(?bool $autoValide): \App\Entity\Products
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAutoValide', [$autoValide]);

        return parent::setAutoValide($autoValide);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategory(): ?\App\Entity\Categories
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', []);

        return parent::getCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategory(?\App\Entity\Categories $categoryService): \App\Entity\Products
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategory', [$categoryService]);

        return parent::setCategory($categoryService);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoto(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoto', []);

        return parent::getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoto(?string $photo): \App\Entity\Products
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoto', [$photo]);

        return parent::setPhoto($photo);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage($image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getOption(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOption', []);

        return parent::getOption();
    }

    /**
     * {@inheritDoc}
     */
    public function addOption(\App\Entity\Option $nameOption): \App\Entity\Products
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOption', [$nameOption]);

        return parent::addOption($nameOption);
    }

    /**
     * {@inheritDoc}
     */
    public function removeNameOption(\App\Entity\Option $nameOption): \App\Entity\Products
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeNameOption', [$nameOption]);

        return parent::removeNameOption($nameOption);
    }

    /**
     * {@inheritDoc}
     */
    public function getSupprime(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSupprime', []);

        return parent::getSupprime();
    }

    /**
     * {@inheritDoc}
     */
    public function setSupprime(int $supprime): \App\Entity\Products
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSupprime', [$supprime]);

        return parent::setSupprime($supprime);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoryProducts(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoryProducts', []);

        return parent::getCategoryProducts();
    }

    /**
     * {@inheritDoc}
     */
    public function addCategoryProduct(\App\Entity\CategoryProduct $categoryProduct): \App\Entity\Products
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCategoryProduct', [$categoryProduct]);

        return parent::addCategoryProduct($categoryProduct);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCategoryProduct(\App\Entity\CategoryProduct $categoryProduct): \App\Entity\Products
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCategoryProduct', [$categoryProduct]);

        return parent::removeCategoryProduct($categoryProduct);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdProvider(): ?\App\Entity\Provider
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdProvider', []);

        return parent::getIdProvider();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdProvider(?\App\Entity\Provider $id_provider): \App\Entity\Products
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdProvider', [$id_provider]);

        return parent::setIdProvider($id_provider);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlannedCleanings(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlannedCleanings', []);

        return parent::getPlannedCleanings();
    }

    /**
     * {@inheritDoc}
     */
    public function addPlannedCleaning(\App\Entity\PlannedCleaning $plannedCleaning): \App\Entity\Products
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPlannedCleaning', [$plannedCleaning]);

        return parent::addPlannedCleaning($plannedCleaning);
    }

    /**
     * {@inheritDoc}
     */
    public function removePlannedCleaning(\App\Entity\PlannedCleaning $plannedCleaning): \App\Entity\Products
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePlannedCleaning', [$plannedCleaning]);

        return parent::removePlannedCleaning($plannedCleaning);
    }

}
