<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MooveeUsers extends \App\Entity\MooveeUsers implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'id', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'first_name', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'last_name', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'email', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'phone_number', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'code_company', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'number_and_street', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'zip_code', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'city', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'customerToken', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'pwResetToken', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'created_date', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'updated_date', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'username', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'password', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'salt', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'roles', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'plainPassword', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'oldPassword', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'role', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'mooveeUserHasCars', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'Provider', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'plannedCleanings', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'planings', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'is_deleted', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'creditCards', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'verifyToken', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'googleToken', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'subscribe'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'id', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'first_name', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'last_name', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'email', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'phone_number', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'code_company', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'number_and_street', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'zip_code', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'city', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'customerToken', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'pwResetToken', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'created_date', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'updated_date', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'username', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'password', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'salt', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'roles', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'plainPassword', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'oldPassword', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'role', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'mooveeUserHasCars', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'Provider', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'plannedCleanings', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'planings', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'is_deleted', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'creditCards', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'verifyToken', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'googleToken', '' . "\0" . 'App\\Entity\\MooveeUsers' . "\0" . 'subscribe'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MooveeUsers $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstName', []);

        return parent::getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstName(?string $first_name): \App\Entity\MooveeUsers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstName', [$first_name]);

        return parent::setFirstName($first_name);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastName', []);

        return parent::getLastName();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastName(?string $last_name): \App\Entity\MooveeUsers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastName', [$last_name]);

        return parent::setLastName($last_name);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(string $email): \App\Entity\MooveeUsers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoneNumber(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoneNumber', []);

        return parent::getPhoneNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoneNumber(string $phone_number): \App\Entity\MooveeUsers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoneNumber', [$phone_number]);

        return parent::setPhoneNumber($phone_number);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeCompany(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeCompany', []);

        return parent::getCodeCompany();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeCompany(?string $code_company): \App\Entity\MooveeUsers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeCompany', [$code_company]);

        return parent::setCodeCompany($code_company);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumberAndStreet(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumberAndStreet', []);

        return parent::getNumberAndStreet();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumberAndStreet(?string $number_and_street): \App\Entity\MooveeUsers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumberAndStreet', [$number_and_street]);

        return parent::setNumberAndStreet($number_and_street);
    }

    /**
     * {@inheritDoc}
     */
    public function getZipCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZipCode', []);

        return parent::getZipCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setZipCode(?string $zip_code): \App\Entity\MooveeUsers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZipCode', [$zip_code]);

        return parent::setZipCode($zip_code);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', []);

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity(?string $city): \App\Entity\MooveeUsers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', [$city]);

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerToken(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerToken', []);

        return parent::getCustomerToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerToken(?string $customerToken): \App\Entity\MooveeUsers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerToken', [$customerToken]);

        return parent::setCustomerToken($customerToken);
    }

    /**
     * {@inheritDoc}
     */
    public function getPwResetToken(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPwResetToken', []);

        return parent::getPwResetToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setPwResetToken(?\DateTimeInterface $pwResetToken): \App\Entity\MooveeUsers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPwResetToken', [$pwResetToken]);

        return parent::setPwResetToken($pwResetToken);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedDate', []);

        return parent::getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedDate(?\DateTimeInterface $created_date): \App\Entity\MooveeUsers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedDate', [$created_date]);

        return parent::setCreatedDate($created_date);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedDate', []);

        return parent::getUpdatedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedDate(?\DateTimeInterface $updated_date): \App\Entity\MooveeUsers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedDate', [$updated_date]);

        return parent::setUpdatedDate($updated_date);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername(string $username): \App\Entity\MooveeUsers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', [$username]);

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword(string $password): \App\Entity\MooveeUsers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', []);

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function setSalt(string $salt): \App\Entity\MooveeUsers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalt', [$salt]);

        return parent::setSalt($salt);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles(): ?array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoles(array $roles): \App\Entity\MooveeUsers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoles', [$roles]);

        return parent::setRoles($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlainPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlainPassword', []);

        return parent::getPlainPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlainPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlainPassword', [$password]);

        return parent::setPlainPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getOldPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOldPassword', []);

        return parent::getOldPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setOldPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOldPassword', [$password]);

        return parent::setOldPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getRole()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRole', []);

        return parent::getRole();
    }

    /**
     * {@inheritDoc}
     */
    public function setRole($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRole', [$role]);

        return parent::setRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', []);

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function getMooveeUserHasCars(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMooveeUserHasCars', []);

        return parent::getMooveeUserHasCars();
    }

    /**
     * {@inheritDoc}
     */
    public function addMooveeUserHasCar(\App\Entity\MooveeUserHasCar $mooveeUserHasCar): \App\Entity\MooveeUsers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMooveeUserHasCar', [$mooveeUserHasCar]);

        return parent::addMooveeUserHasCar($mooveeUserHasCar);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMooveeUserHasCar(\App\Entity\MooveeUserHasCar $mooveeUserHasCar): \App\Entity\MooveeUsers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMooveeUserHasCar', [$mooveeUserHasCar]);

        return parent::removeMooveeUserHasCar($mooveeUserHasCar);
    }

    /**
     * {@inheritDoc}
     */
    public function getProvider(): ?\App\Entity\Provider
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProvider', []);

        return parent::getProvider();
    }

    /**
     * {@inheritDoc}
     */
    public function setProvider(?\App\Entity\Provider $Provider): \App\Entity\MooveeUsers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProvider', [$Provider]);

        return parent::setProvider($Provider);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlannedCleanings(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlannedCleanings', []);

        return parent::getPlannedCleanings();
    }

    /**
     * {@inheritDoc}
     */
    public function addPlannedCleaning(\App\Entity\PlannedCleaning $plannedCleaning): \App\Entity\MooveeUsers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPlannedCleaning', [$plannedCleaning]);

        return parent::addPlannedCleaning($plannedCleaning);
    }

    /**
     * {@inheritDoc}
     */
    public function removePlannedCleaning(\App\Entity\PlannedCleaning $plannedCleaning): \App\Entity\MooveeUsers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePlannedCleaning', [$plannedCleaning]);

        return parent::removePlannedCleaning($plannedCleaning);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlanings(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlanings', []);

        return parent::getPlanings();
    }

    /**
     * {@inheritDoc}
     */
    public function addPlaning(\App\Entity\Planing $planing): \App\Entity\MooveeUsers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPlaning', [$planing]);

        return parent::addPlaning($planing);
    }

    /**
     * {@inheritDoc}
     */
    public function removePlaning(\App\Entity\Planing $planing): \App\Entity\MooveeUsers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePlaning', [$planing]);

        return parent::removePlaning($planing);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsDeleted(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsDeleted', []);

        return parent::getIsDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsDeleted(?bool $is_deleted): \App\Entity\MooveeUsers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsDeleted', [$is_deleted]);

        return parent::setIsDeleted($is_deleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreditCards(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreditCards', []);

        return parent::getCreditCards();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreditCard(\App\Entity\CreditCard $creditCard): \App\Entity\MooveeUsers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreditCard', [$creditCard]);

        return parent::addCreditCard($creditCard);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreditCard(\App\Entity\CreditCard $creditCard): \App\Entity\MooveeUsers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreditCard', [$creditCard]);

        return parent::removeCreditCard($creditCard);
    }

    /**
     * {@inheritDoc}
     */
    public function getVerifyToken(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVerifyToken', []);

        return parent::getVerifyToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setVerifyToken(?string $verifyToken): \App\Entity\MooveeUsers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVerifyToken', [$verifyToken]);

        return parent::setVerifyToken($verifyToken);
    }

    /**
     * {@inheritDoc}
     */
    public function getClients(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClients', []);

        return parent::getClients();
    }

    /**
     * {@inheritDoc}
     */
    public function getGoogleToken(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGoogleToken', []);

        return parent::getGoogleToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setGoogleToken(?bool $googleToken): \App\Entity\MooveeUsers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGoogleToken', [$googleToken]);

        return parent::setGoogleToken($googleToken);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubscribe(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubscribe', []);

        return parent::getSubscribe();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubscribe(?bool $subscribe): \App\Entity\MooveeUsers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubscribe', [$subscribe]);

        return parent::setSubscribe($subscribe);
    }

}
