<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MooveeCompany extends \App\Entity\MooveeCompany implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\MooveeCompany' . "\0" . 'id', '' . "\0" . 'App\\Entity\\MooveeCompany' . "\0" . 'name', '' . "\0" . 'App\\Entity\\MooveeCompany' . "\0" . 'address', '' . "\0" . 'App\\Entity\\MooveeCompany' . "\0" . 'phone_number', '' . "\0" . 'App\\Entity\\MooveeCompany' . "\0" . 'code_entreprise', '' . "\0" . 'App\\Entity\\MooveeCompany' . "\0" . 'contact_entreprise', '' . "\0" . 'App\\Entity\\MooveeCompany' . "\0" . 'contact_mail_entreprise', '' . "\0" . 'App\\Entity\\MooveeCompany' . "\0" . 'created_date', '' . "\0" . 'App\\Entity\\MooveeCompany' . "\0" . 'updated_date', '' . "\0" . 'App\\Entity\\MooveeCompany' . "\0" . 'photo', '' . "\0" . 'App\\Entity\\MooveeCompany' . "\0" . 'image', '' . "\0" . 'App\\Entity\\MooveeCompany' . "\0" . 'parkings'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\MooveeCompany' . "\0" . 'id', '' . "\0" . 'App\\Entity\\MooveeCompany' . "\0" . 'name', '' . "\0" . 'App\\Entity\\MooveeCompany' . "\0" . 'address', '' . "\0" . 'App\\Entity\\MooveeCompany' . "\0" . 'phone_number', '' . "\0" . 'App\\Entity\\MooveeCompany' . "\0" . 'code_entreprise', '' . "\0" . 'App\\Entity\\MooveeCompany' . "\0" . 'contact_entreprise', '' . "\0" . 'App\\Entity\\MooveeCompany' . "\0" . 'contact_mail_entreprise', '' . "\0" . 'App\\Entity\\MooveeCompany' . "\0" . 'created_date', '' . "\0" . 'App\\Entity\\MooveeCompany' . "\0" . 'updated_date', '' . "\0" . 'App\\Entity\\MooveeCompany' . "\0" . 'photo', '' . "\0" . 'App\\Entity\\MooveeCompany' . "\0" . 'image', '' . "\0" . 'App\\Entity\\MooveeCompany' . "\0" . 'parkings'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MooveeCompany $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \App\Entity\MooveeCompany
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', []);

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress(string $address): \App\Entity\MooveeCompany
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', [$address]);

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoneNumber(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoneNumber', []);

        return parent::getPhoneNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoneNumber(string $phone_number): \App\Entity\MooveeCompany
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoneNumber', [$phone_number]);

        return parent::setPhoneNumber($phone_number);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeEntreprise(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeEntreprise', []);

        return parent::getCodeEntreprise();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeEntreprise(string $code_entreprise): \App\Entity\MooveeCompany
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeEntreprise', [$code_entreprise]);

        return parent::setCodeEntreprise($code_entreprise);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactEntreprise(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactEntreprise', []);

        return parent::getContactEntreprise();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactEntreprise(string $contact_entreprise): \App\Entity\MooveeCompany
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactEntreprise', [$contact_entreprise]);

        return parent::setContactEntreprise($contact_entreprise);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactMailEntreprise(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactMailEntreprise', []);

        return parent::getContactMailEntreprise();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactMailEntreprise(string $contact_mail_entreprise): \App\Entity\MooveeCompany
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactMailEntreprise', [$contact_mail_entreprise]);

        return parent::setContactMailEntreprise($contact_mail_entreprise);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedDate', []);

        return parent::getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedDate(\DateTimeInterface $created_date): \App\Entity\MooveeCompany
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedDate', [$created_date]);

        return parent::setCreatedDate($created_date);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedDate', []);

        return parent::getUpdatedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedDate(?\DateTimeInterface $updated_date): \App\Entity\MooveeCompany
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedDate', [$updated_date]);

        return parent::setUpdatedDate($updated_date);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoto(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoto', []);

        return parent::getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoto(string $photo): \App\Entity\MooveeCompany
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoto', [$photo]);

        return parent::setPhoto($photo);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage($image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getParkings(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParkings', []);

        return parent::getParkings();
    }

    /**
     * {@inheritDoc}
     */
    public function addParking(\App\Entity\Parkings $parking): \App\Entity\MooveeCompany
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addParking', [$parking]);

        return parent::addParking($parking);
    }

    /**
     * {@inheritDoc}
     */
    public function removeParking(\App\Entity\Parkings $parking): \App\Entity\MooveeCompany
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeParking', [$parking]);

        return parent::removeParking($parking);
    }

}
