<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MooveeCar extends \App\Entity\MooveeCar implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\MooveeCar' . "\0" . 'id', '' . "\0" . 'App\\Entity\\MooveeCar' . "\0" . 'brand_car', '' . "\0" . 'App\\Entity\\MooveeCar' . "\0" . 'model_car', '' . "\0" . 'App\\Entity\\MooveeCar' . "\0" . 'is_deleted', '' . "\0" . 'App\\Entity\\MooveeCar' . "\0" . 'category_car', '' . "\0" . 'App\\Entity\\MooveeCar' . "\0" . 'mooveeUserHasCars'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\MooveeCar' . "\0" . 'id', '' . "\0" . 'App\\Entity\\MooveeCar' . "\0" . 'brand_car', '' . "\0" . 'App\\Entity\\MooveeCar' . "\0" . 'model_car', '' . "\0" . 'App\\Entity\\MooveeCar' . "\0" . 'is_deleted', '' . "\0" . 'App\\Entity\\MooveeCar' . "\0" . 'category_car', '' . "\0" . 'App\\Entity\\MooveeCar' . "\0" . 'mooveeUserHasCars'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MooveeCar $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getBrandCar(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBrandCar', []);

        return parent::getBrandCar();
    }

    /**
     * {@inheritDoc}
     */
    public function setBrandCar(string $brand_car): \App\Entity\MooveeCar
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBrandCar', [$brand_car]);

        return parent::setBrandCar($brand_car);
    }

    /**
     * {@inheritDoc}
     */
    public function getModelCar(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModelCar', []);

        return parent::getModelCar();
    }

    /**
     * {@inheritDoc}
     */
    public function setModelCar(string $model_car): \App\Entity\MooveeCar
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModelCar', [$model_car]);

        return parent::setModelCar($model_car);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsDeleted(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsDeleted', []);

        return parent::getIsDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsDeleted(?int $is_deleted): \App\Entity\MooveeCar
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsDeleted', [$is_deleted]);

        return parent::setIsDeleted($is_deleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoryCar(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoryCar', []);

        return parent::getCategoryCar();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategoryCar(string $category_car): \App\Entity\MooveeCar
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategoryCar', [$category_car]);

        return parent::setCategoryCar($category_car);
    }

    /**
     * {@inheritDoc}
     */
    public function getMooveeUserHasCars(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMooveeUserHasCars', []);

        return parent::getMooveeUserHasCars();
    }

    /**
     * {@inheritDoc}
     */
    public function addMooveeUserHasCar(\App\Entity\MooveeUserHasCar $mooveeUserHasCar): \App\Entity\MooveeCar
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMooveeUserHasCar', [$mooveeUserHasCar]);

        return parent::addMooveeUserHasCar($mooveeUserHasCar);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMooveeUserHasCar(\App\Entity\MooveeUserHasCar $mooveeUserHasCar): \App\Entity\MooveeCar
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMooveeUserHasCar', [$mooveeUserHasCar]);

        return parent::removeMooveeUserHasCar($mooveeUserHasCar);
    }

}
