<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MooveeUserHasCar extends \App\Entity\MooveeUserHasCar implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\MooveeUserHasCar' . "\0" . 'id', '' . "\0" . 'App\\Entity\\MooveeUserHasCar' . "\0" . 'user_has_car_id_user', '' . "\0" . 'App\\Entity\\MooveeUserHasCar' . "\0" . 'user_has_car_id_car', '' . "\0" . 'App\\Entity\\MooveeUserHasCar' . "\0" . 'user_has_car_nickname_car', '' . "\0" . 'App\\Entity\\MooveeUserHasCar' . "\0" . 'created_date', '' . "\0" . 'App\\Entity\\MooveeUserHasCar' . "\0" . 'updated_date', '' . "\0" . 'App\\Entity\\MooveeUserHasCar' . "\0" . 'plannedCleanings', '' . "\0" . 'App\\Entity\\MooveeUserHasCar' . "\0" . 'is_deleted', '' . "\0" . 'App\\Entity\\MooveeUserHasCar' . "\0" . 'space_number'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\MooveeUserHasCar' . "\0" . 'id', '' . "\0" . 'App\\Entity\\MooveeUserHasCar' . "\0" . 'user_has_car_id_user', '' . "\0" . 'App\\Entity\\MooveeUserHasCar' . "\0" . 'user_has_car_id_car', '' . "\0" . 'App\\Entity\\MooveeUserHasCar' . "\0" . 'user_has_car_nickname_car', '' . "\0" . 'App\\Entity\\MooveeUserHasCar' . "\0" . 'created_date', '' . "\0" . 'App\\Entity\\MooveeUserHasCar' . "\0" . 'updated_date', '' . "\0" . 'App\\Entity\\MooveeUserHasCar' . "\0" . 'plannedCleanings', '' . "\0" . 'App\\Entity\\MooveeUserHasCar' . "\0" . 'is_deleted', '' . "\0" . 'App\\Entity\\MooveeUserHasCar' . "\0" . 'space_number'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MooveeUserHasCar $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUserHasCarIdUser(): ?\App\Entity\MooveeUsers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserHasCarIdUser', []);

        return parent::getUserHasCarIdUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserHasCarIdUser(?\App\Entity\MooveeUsers $user_has_car_id_user): \App\Entity\MooveeUserHasCar
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserHasCarIdUser', [$user_has_car_id_user]);

        return parent::setUserHasCarIdUser($user_has_car_id_user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserHasCarIdCar(): ?\App\Entity\MooveeCar
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserHasCarIdCar', []);

        return parent::getUserHasCarIdCar();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserHasCarIdCar(?\App\Entity\MooveeCar $user_has_car_id_car): \App\Entity\MooveeUserHasCar
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserHasCarIdCar', [$user_has_car_id_car]);

        return parent::setUserHasCarIdCar($user_has_car_id_car);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserHasCarNicknameCar(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserHasCarNicknameCar', []);

        return parent::getUserHasCarNicknameCar();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserHasCarNicknameCar(string $user_has_car_nickname_car): \App\Entity\MooveeUserHasCar
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserHasCarNicknameCar', [$user_has_car_nickname_car]);

        return parent::setUserHasCarNicknameCar($user_has_car_nickname_car);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedDate', []);

        return parent::getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedDate(\DateTimeInterface $created_date): \App\Entity\MooveeUserHasCar
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedDate', [$created_date]);

        return parent::setCreatedDate($created_date);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedDate', []);

        return parent::getUpdatedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedDate(?\DateTimeInterface $updated_date): \App\Entity\MooveeUserHasCar
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedDate', [$updated_date]);

        return parent::setUpdatedDate($updated_date);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlannedCleanings(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlannedCleanings', []);

        return parent::getPlannedCleanings();
    }

    /**
     * {@inheritDoc}
     */
    public function addPlannedCleaning(\App\Entity\PlannedCleaning $plannedCleaning): \App\Entity\MooveeUserHasCar
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPlannedCleaning', [$plannedCleaning]);

        return parent::addPlannedCleaning($plannedCleaning);
    }

    /**
     * {@inheritDoc}
     */
    public function removePlannedCleaning(\App\Entity\PlannedCleaning $plannedCleaning): \App\Entity\MooveeUserHasCar
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePlannedCleaning', [$plannedCleaning]);

        return parent::removePlannedCleaning($plannedCleaning);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsDeleted(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsDeleted', []);

        return parent::getIsDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsDeleted(?bool $is_deleted): \App\Entity\MooveeUserHasCar
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsDeleted', [$is_deleted]);

        return parent::setIsDeleted($is_deleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpaceNumber(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpaceNumber', []);

        return parent::getSpaceNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setSpaceNumber(?string $space_number): \App\Entity\MooveeUserHasCar
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpaceNumber', [$space_number]);

        return parent::setSpaceNumber($space_number);
    }

}
