<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Categories extends \App\Entity\Categories implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Categories' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Categories' . "\0" . 'category', '' . "\0" . 'App\\Entity\\Categories' . "\0" . 'idcat', '' . "\0" . 'App\\Entity\\Categories' . "\0" . 'cats', '' . "\0" . 'App\\Entity\\Categories' . "\0" . 'idservice', '' . "\0" . 'App\\Entity\\Categories' . "\0" . 'products', '' . "\0" . 'App\\Entity\\Categories' . "\0" . 'needCar', '' . "\0" . 'App\\Entity\\Categories' . "\0" . 'photo', '' . "\0" . 'App\\Entity\\Categories' . "\0" . 'image'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Categories' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Categories' . "\0" . 'category', '' . "\0" . 'App\\Entity\\Categories' . "\0" . 'idcat', '' . "\0" . 'App\\Entity\\Categories' . "\0" . 'cats', '' . "\0" . 'App\\Entity\\Categories' . "\0" . 'idservice', '' . "\0" . 'App\\Entity\\Categories' . "\0" . 'products', '' . "\0" . 'App\\Entity\\Categories' . "\0" . 'needCar', '' . "\0" . 'App\\Entity\\Categories' . "\0" . 'photo', '' . "\0" . 'App\\Entity\\Categories' . "\0" . 'image'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Categories $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCategory(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', []);

        return parent::getCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategory(string $category): \App\Entity\Categories
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategory', [$category]);

        return parent::setCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function getNeedCar(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNeedCar', []);

        return parent::getNeedCar();
    }

    /**
     * {@inheritDoc}
     */
    public function setNeedCar(?bool $needCar): \App\Entity\Categories
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNeedCar', [$needCar]);

        return parent::setNeedCar($needCar);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCategory(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCategory', []);

        return parent::getIdCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function addIdCategory(\App\Entity\CategoryProvider $cat): \App\Entity\Categories
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIdCategory', [$cat]);

        return parent::addIdCategory($cat);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdProduct(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdProduct', []);

        return parent::getIdProduct();
    }

    /**
     * {@inheritDoc}
     */
    public function addIdProduct(\App\Entity\Products $products): \App\Entity\Categories
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIdProduct', [$products]);

        return parent::addIdProduct($products);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIdProduct(\App\Entity\Products $products): \App\Entity\Categories
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIdProduct', [$products]);

        return parent::removeIdProduct($products);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoto(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoto', []);

        return parent::getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoto(string $photo): \App\Entity\Categories
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoto', [$photo]);

        return parent::setPhoto($photo);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage($image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getService(): ?\App\Entity\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getService', []);

        return parent::getService();
    }

    /**
     * {@inheritDoc}
     */
    public function setService(\App\Entity\Service $idservice): \App\Entity\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setService', [$idservice]);

        return parent::setService($idservice);
    }

}
