<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CreditCard extends \App\Entity\CreditCard implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\CreditCard' . "\0" . 'id', '' . "\0" . 'App\\Entity\\CreditCard' . "\0" . 'customerId', '' . "\0" . 'App\\Entity\\CreditCard' . "\0" . 'monthValidity', '' . "\0" . 'App\\Entity\\CreditCard' . "\0" . 'yearValidity', '' . "\0" . 'App\\Entity\\CreditCard' . "\0" . 'lastDigits', '' . "\0" . 'App\\Entity\\CreditCard' . "\0" . 'cardToken', '' . "\0" . 'App\\Entity\\CreditCard' . "\0" . 'cardType'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\CreditCard' . "\0" . 'id', '' . "\0" . 'App\\Entity\\CreditCard' . "\0" . 'customerId', '' . "\0" . 'App\\Entity\\CreditCard' . "\0" . 'monthValidity', '' . "\0" . 'App\\Entity\\CreditCard' . "\0" . 'yearValidity', '' . "\0" . 'App\\Entity\\CreditCard' . "\0" . 'lastDigits', '' . "\0" . 'App\\Entity\\CreditCard' . "\0" . 'cardToken', '' . "\0" . 'App\\Entity\\CreditCard' . "\0" . 'cardType'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CreditCard $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerId(): ?\App\Entity\MooveeUsers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerId', []);

        return parent::getCustomerId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerId(?\App\Entity\MooveeUsers $customerId): \App\Entity\CreditCard
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerId', [$customerId]);

        return parent::setCustomerId($customerId);
    }

    /**
     * {@inheritDoc}
     */
    public function getMonthValidity(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMonthValidity', []);

        return parent::getMonthValidity();
    }

    /**
     * {@inheritDoc}
     */
    public function setMonthValidity(string $monthValidity): \App\Entity\CreditCard
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMonthValidity', [$monthValidity]);

        return parent::setMonthValidity($monthValidity);
    }

    /**
     * {@inheritDoc}
     */
    public function getYearValidity(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getYearValidity', []);

        return parent::getYearValidity();
    }

    /**
     * {@inheritDoc}
     */
    public function setYearValidity(string $yearValidity): \App\Entity\CreditCard
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setYearValidity', [$yearValidity]);

        return parent::setYearValidity($yearValidity);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastDigits(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastDigits', []);

        return parent::getLastDigits();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastDigits(string $lastDigits): \App\Entity\CreditCard
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastDigits', [$lastDigits]);

        return parent::setLastDigits($lastDigits);
    }

    /**
     * {@inheritDoc}
     */
    public function getCardToken(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCardToken', []);

        return parent::getCardToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setCardToken(string $cardToken): \App\Entity\CreditCard
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCardToken', [$cardToken]);

        return parent::setCardToken($cardToken);
    }

    /**
     * {@inheritDoc}
     */
    public function getCardType(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCardType', []);

        return parent::getCardType();
    }

    /**
     * {@inheritDoc}
     */
    public function setCardType(string $cardType): \App\Entity\CreditCard
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCardType', [$cardType]);

        return parent::setCardType($cardType);
    }

}
