<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNHONPpK\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNHONPpK/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerNHONPpK.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerNHONPpK\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerNHONPpK\srcApp_KernelProdContainer([
    'container.build_hash' => 'NHONPpK',
    'container.build_id' => 'b6a83fdb',
    'container.build_time' => 1626098881,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNHONPpK');
