<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\CmsController' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/ControllerTrait.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
include_once $this->targetDirs[3].'/src/Controller/CmsController.php';

$a = ($this->privates['App\\Repository\\PlannedCleaningOptionsRepository'] ?? $this->load('getPlannedCleaningOptionsRepositoryService.php'));

$this->services['App\\Controller\\CmsController'] = $instance = new \App\Controller\CmsController(($this->privates['App\\Repository\\ReductionRepository'] ?? $this->load('getReductionRepositoryService.php')), $a, ($this->privates['App\\Repository\\PlannedCleaningRepository'] ?? $this->load('getPlannedCleaningRepositoryService.php')), ($this->privates['App\\Repository\\CreditCardRepository'] ?? $this->load('getCreditCardRepositoryService.php')), ($this->privates['App\\Repository\\CategoryProductRepository'] ?? $this->load('getCategoryProductRepositoryService.php')), ($this->privates['App\\Repository\\ProductsRepository'] ?? $this->load('getProductsRepositoryService.php')), ($this->privates['App\\Repository\\MooveeUserHasCarRepository'] ?? $this->load('getMooveeUserHasCarRepositoryService.php')), ($this->services['swiftmailer.mailer.default'] ?? $this->load('getSwiftmailer_Mailer_DefaultService.php')), ($this->privates['App\\Repository\\MooveeCompanyRepository'] ?? $this->load('getMooveeCompanyRepositoryService.php')), ($this->privates['App\\Repository\\AvailabilityRepository'] ?? $this->load('getAvailabilityRepositoryService.php')), ($this->privates['App\\Repository\\CategoryOptionRepository'] ?? $this->load('getCategoryOptionRepositoryService.php')), ($this->privates['App\\Repository\\CategoriesRepository'] ?? $this->load('getCategoriesRepositoryService.php')), ($this->privates['App\\Repository\\MooveeCarRepository'] ?? $this->load('getMooveeCarRepositoryService.php')), $a, ($this->privates['App\\Repository\\OptionRepository'] ?? $this->load('getOptionRepositoryService.php')), ($this->privates['App\\Repository\\ProviderRepository'] ?? $this->load('getProviderRepositoryService.php')), ($this->privates['App\\Repository\\GoogleCalendarApiRepository'] ?? $this->load('getGoogleCalendarApiRepositoryService.php')));

$instance->setContainer(($this->privates['.service_locator.KTVqfp6'] ?? $this->load('get_ServiceLocator_KTVqfp6Service.php'))->withContext('App\\Controller\\CmsController', $this));

return $instance;
