<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\CleanerController' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/ControllerTrait.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
include_once $this->targetDirs[3].'/src/Controller/CleanerController.php';

$this->services['App\\Controller\\CleanerController'] = $instance = new \App\Controller\CleanerController(($this->privates['App\\Repository\\PlannedCleaningRepository'] ?? $this->load('getPlannedCleaningRepositoryService.php')), ($this->privates['App\\Repository\\PlaningRepository'] ?? $this->load('getPlaningRepositoryService.php')), ($this->privates['App\\Repository\\MooveeUsersRepository'] ?? $this->load('getMooveeUsersRepositoryService.php')));

$instance->setContainer(($this->privates['.service_locator.KTVqfp6'] ?? $this->load('get_ServiceLocator_KTVqfp6Service.php'))->withContext('App\\Controller\\CleanerController', $this));

return $instance;
