<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'form.registry' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormRegistryInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/FormRegistry.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/FormExtensionInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/Extension/DependencyInjection/DependencyInjectionExtension.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/ResolvedFormTypeFactoryInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/ResolvedFormTypeFactory.php';

return $this->privates['form.registry'] = new \Symfony\Component\Form\FormRegistry([0 => new \Symfony\Component\Form\Extension\DependencyInjection\DependencyInjectionExtension(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Form\\AdminPassType' => ['privates', 'App\\Form\\AdminPassType', 'getAdminPassTypeService.php', true],
    'App\\Form\\AvailabilityType' => ['privates', 'App\\Form\\AvailabilityType', 'getAvailabilityTypeService.php', true],
    'App\\Form\\CarType' => ['privates', 'App\\Form\\CarType', 'getCarTypeService.php', true],
    'App\\Form\\CatLocationType' => ['privates', 'App\\Form\\CatLocationType', 'getCatLocationTypeService.php', true],
    'App\\Form\\CatOptionType' => ['privates', 'App\\Form\\CatOptionType', 'getCatOptionTypeService.php', true],
    'App\\Form\\CatProductType' => ['privates', 'App\\Form\\CatProductType', 'getCatProductTypeService.php', true],
    'App\\Form\\CategoriesType' => ['privates', 'App\\Form\\CategoriesType', 'getCategoriesTypeService.php', true],
    'App\\Form\\ClientType' => ['privates', 'App\\Form\\ClientType', 'getClientTypeService.php', true],
    'App\\Form\\CompanyType' => ['privates', 'App\\Form\\CompanyType', 'getCompanyTypeService.php', true],
    'App\\Form\\CreditCardType' => ['privates', 'App\\Form\\CreditCardType', 'getCreditCardTypeService.php', true],
    'App\\Form\\ForgetPassType' => ['privates', 'App\\Form\\ForgetPassType', 'getForgetPassTypeService.php', true],
    'App\\Form\\HorraireType' => ['privates', 'App\\Form\\HorraireType', 'getHorraireTypeService.php', true],
    'App\\Form\\OptionType' => ['privates', 'App\\Form\\OptionType', 'getOptionTypeService.php', true],
    'App\\Form\\OrderType' => ['privates', 'App\\Form\\OrderType', 'getOrderTypeService.php', true],
    'App\\Form\\ParkingType' => ['privates', 'App\\Form\\ParkingType', 'getParkingTypeService.php', true],
    'App\\Form\\PassType' => ['privates', 'App\\Form\\PassType', 'getPassTypeService.php', true],
    'App\\Form\\PhotoParkingType' => ['privates', 'App\\Form\\PhotoParkingType', 'getPhotoParkingTypeService.php', true],
    'App\\Form\\PlannedCleaningType' => ['privates', 'App\\Form\\PlannedCleaningType', 'getPlannedCleaningTypeService.php', true],
    'App\\Form\\ProductType' => ['privates', 'App\\Form\\ProductType', 'getProductTypeService.php', true],
    'App\\Form\\ProviderType' => ['privates', 'App\\Form\\ProviderType', 'getProviderTypeService.php', true],
    'App\\Form\\RecurrenceAvaibleType' => ['privates', 'App\\Form\\RecurrenceAvaibleType', 'getRecurrenceAvaibleTypeService.php', true],
    'App\\Form\\ReductionType' => ['privates', 'App\\Form\\ReductionType', 'getReductionTypeService.php', true],
    'App\\Form\\ServiceType' => ['privates', 'App\\Form\\ServiceType', 'getServiceTypeService.php', true],
    'App\\Form\\SignUpType' => ['privates', 'App\\Form\\SignUpType', 'getSignUpTypeService.php', true],
    'App\\Form\\Step2Type' => ['privates', 'App\\Form\\Step2Type', 'getStep2TypeService.php', true],
    'App\\Form\\SupportType' => ['privates', 'App\\Form\\SupportType', 'getSupportTypeService.php', true],
    'App\\Form\\UserHasCarType' => ['privates', 'App\\Form\\UserHasCarType', 'getUserHasCarTypeService.php', true],
    'App\\Form\\UserType' => ['privates', 'App\\Form\\UserType', 'getUserTypeService.php', true],
    'FOS\\CKEditorBundle\\Form\\Type\\CKEditorType' => ['privates', 'fos_ck_editor.form.type', 'getFosCkEditor_Form_TypeService.php', true],
    'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType' => ['privates', 'form.type.entity', 'getForm_Type_EntityService.php', true],
    'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => ['privates', 'form.type.choice', 'getForm_Type_ChoiceService.php', true],
    'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => ['privates', 'form.type.form', 'getForm_Type_FormService.php', true],
]), ['Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_extension.form.transformation_failure_handling'] ?? $this->load('getForm_TypeExtension_Form_TransformationFailureHandlingService.php'));
    yield 1 => ($this->privates['form.type_extension.form.http_foundation'] ?? $this->load('getForm_TypeExtension_Form_HttpFoundationService.php'));
    yield 2 => ($this->privates['form.type_extension.form.validator'] ?? $this->load('getForm_TypeExtension_Form_ValidatorService.php'));
    yield 3 => ($this->privates['form.type_extension.upload.validator'] ?? $this->load('getForm_TypeExtension_Upload_ValidatorService.php'));
    yield 4 => ($this->privates['form.type_extension.csrf'] ?? $this->load('getForm_TypeExtension_CsrfService.php'));
    yield 5 => ($this->privates['craue.form.flow.form_extension'] ?? ($this->privates['craue.form.flow.form_extension'] = new \Craue\FormFlowBundle\Form\Extension\FormFlowFormExtension()));
}, 6), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\RepeatedType' => new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_extension.repeated.validator'] ?? ($this->privates['form.type_extension.repeated.validator'] = new \Symfony\Component\Form\Extension\Validator\Type\RepeatedTypeValidatorExtension()));
}, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\SubmitType' => new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_extension.submit.validator'] ?? ($this->privates['form.type_extension.submit.validator'] = new \Symfony\Component\Form\Extension\Validator\Type\SubmitTypeValidatorExtension()));
}, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\HiddenType' => new RewindableGenerator(function () {
    yield 0 => ($this->privates['craue.form.flow.hidden_field_extension'] ?? ($this->privates['craue.form.flow.hidden_field_extension'] = new \Craue\FormFlowBundle\Form\Extension\FormFlowHiddenFieldExtension()));
}, 1)], new RewindableGenerator(function () {
    yield 0 => ($this->privates['form.type_guesser.validator'] ?? $this->load('getForm_TypeGuesser_ValidatorService.php'));
    yield 1 => ($this->privates['form.type_guesser.doctrine'] ?? $this->load('getForm_TypeGuesser_DoctrineService.php'));
}, 2))], new \Symfony\Component\Form\ResolvedFormTypeFactory());
