<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\ProviderController' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/ControllerTrait.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
include_once $this->targetDirs[3].'/src/Controller/ProviderController.php';

$this->services['App\\Controller\\ProviderController'] = $instance = new \App\Controller\ProviderController(($this->privates['App\\Repository\\ProviderRepository'] ?? $this->load('getProviderRepositoryService.php')), ($this->privates['App\\Repository\\MooveeUsersRepository'] ?? $this->load('getMooveeUsersRepositoryService.php')), ($this->privates['App\\Repository\\ParkingsRepository'] ?? $this->load('getParkingsRepositoryService.php')), ($this->privates['App\\Repository\\CategoryProviderRepository'] ?? $this->load('getCategoryProviderRepositoryService.php')), ($this->privates['App\\Repository\\PlannedCleaningRepository'] ?? $this->load('getPlannedCleaningRepositoryService.php')), ($this->privates['App\\Repository\\AvailabilityRepository'] ?? $this->load('getAvailabilityRepositoryService.php')), ($this->privates['App\\Repository\\EventsFromGCalendarRepository'] ?? $this->load('getEventsFromGCalendarRepositoryService.php')));

$instance->setContainer(($this->privates['.service_locator.KTVqfp6'] ?? $this->load('get_ServiceLocator_KTVqfp6Service.php'))->withContext('App\\Controller\\ProviderController', $this));

return $instance;
