<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Form\Step2Type' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[3].'/src/Form/Step2Type.php';

return $this->privates['App\\Form\\Step2Type'] = new \App\Form\Step2Type(($this->privates['security.helper'] ?? $this->load('getSecurity_HelperService.php')), ($this->privates['App\\Repository\\MooveeCarRepository'] ?? $this->load('getMooveeCarRepositoryService.php')));
